pantheon-tweaks/pantheon-tweaks

src/Tweaks.vala

- Remove unused `plug` and `current_grid`
Review in "Hide whitespace changes" mode.

Tweaks: Clean code

---

src/Util.vala

- Lint using vala-lint
- Remove unused `file_exists` and `create_markup`

Util: Clean code

---

src/Panes/AppearancePane.vala

Appearance: Clean code

---

README.md

Use codename instead of version numbering as was with previous tweaks and point to previous tweaks in description (#40).

README: Clarify the supported version and the solution for failing installation

---

src/Panes/AppearancePane.vala

Fix prefer dark style switch state not loading

---

src/Panes/FilesPane.vala

FilesPane: Remove single-click option

---

meson.build

Which elementary and GitHub recommends

meson: Use Semantic Versioning

---

src/Panes/AppearancePane.vala

Fixes elementary-tweaks/elementary-tweaks#98 ("Replace Maximize to Minimize")
Fixes #75 ("elementary Reversed")

AppearancePane: Add more layout option

---

src/Tweaks.vala

Because of elementary-tweaks/elementary-tweaks#149

Tweaks: 'Tweak Pantheon'

---

data/pantheon-tweaks.appdata.xml.in
debian/changelog
debian/control
debian/rules

* Deprecate dbg symbol package
* Update changelog for 1.0.0

Update packaging and changelog

---

data/pantheon-tweaks.appdata.xml.in
debian/changelog

Release 1.0.0

---

src/Panes/AudiencePane.vala
src/Panes/FilesPane.vala
src/Panes/TerminalPane.vala

We no longer need these old schema since we no longer support Loki which uses them

Remove old schema

---

data/pantheon-tweaks.appdata.xml.in
src/Tweaks.vala
src/Widgets/Categories.vala

Not sure if someone want to use this method but this PR allows accessing to a specific pane in the Plug like [this](https://github.com/elementary/sideload/blob/65f90501fa1773a83c1f06e15cd0bd2e9f7ea617/src/Views/SuccessView.vala#L70)

Support accessing to panes with settings paths

---

src/Panes/AnimationsPane.vala

Add a context comment for the word 'snap'

---

src/Panes/TerminalPane.vala

TerminalPane: Tab bar behavior

---

src/Panes/AppearancePane.vala
src/Settings/ThemeSettings.vala
src/Widgets/Categories.vala

Sort entries in combobox

---

src/Panes/AppearancePane.vala
src/Widgets/Categories.vala

Add buttons to open the theme locations

---

.github/workflows/main.yml
debian/control

As mentioned in https://askubuntu.com/questions/1273027/debian-package-builds-in-my-computer-but-fails-to-build-in-launchpad-and-pbuild

Actions: Fix build failing

---

src/Panes/AppearancePane.vala
src/Panes/FilesPane.vala
src/Panes/FontsPane.vala
src/Panes/MiscPane.vala
src/Panes/TerminalPane.vala
src/Widgets/Categories.vala

If we add new pane, we need to modify PANE_NAME variable too which is not efficient. With this change we no longer need it and just adding the new pane to panes variable is fine.

Efficiently find and match pane name

---

src/Panes/AppearancePane.vala
src/Panes/MiscPane.vala

Update pane icons

---

data/pantheon-tweaks.metainfo.xml.in
debian/changelog
meson.build
src/Tweaks.vala

Add an infobar about migration as discussed in https://github.com/pantheon-tweaks/pantheon-tweaks/issues/187#issuecomment-1879885040

Release 1.1.2

---

debian/copyright
src/Panes/AppearancePane.vala
src/Panes/FilesPane.vala
src/Panes/FontsPane.vala
src/Panes/MiscPane.vala
src/Panes/TerminalPane.vala
src/Settings/AccountsService.vala
src/Settings/GtkSettings.vala
src/Settings/ThemeSettings.vala
src/Settings/XSettings.vala
src/Tweaks.vala
src/Widgets/Categories.vala

Update copyright headers to 2024

---

README.md
data/pantheon-tweaks.metainfo.xml.in

This phrase is confusing with System Settings app on Pantheon, so use different phrase.

docs: Avoid confusing phrase "system settings"

---

io.github.pantheon_tweaks.pantheon-tweaks.yml

I don't see the differences but "home" looks like has no specific meaning in this context, according to the Flathub maintainer.
https://github.com/flathub/flathub/pull/5266#discussion_r1606016979

Use ~ instead of "home"

---

src/MainWindow.vala
src/Tweaks.vala

As suggested in https://github.com/flathub/flathub/pull/5266#issuecomment-2126011058

Show unsupported DE graphically

---

data/pantheon-tweaks.metainfo.xml.in

`GPL-3.0+` is deprecated:
https://spdx.org/licenses/GPL-3.0+.html

metainfo: Update license id

---

io.github.pantheon_tweaks.pantheon-tweaks.yml
meson.build
src/MainWindow.vala
src/Panes/AppearancePane.vala
src/Panes/FilesPane.vala
src/Panes/FontsPane.vala
src/Panes/MiscPane.vala
src/Panes/TerminalPane.vala
src/Tweaks.vala
src/Widgets/Categories.vala

Port to GTK4

---

data/meson.build
data/pantheon-tweaks.gschema.xml
meson.build
src/MainWindow.vala
src/Tweaks.vala

Save and restore window size

---

src/Panes/MiscPane.vala

- Add scale for more intuitive operation

MiscPane: Redesign

---

src/Panes/AppearancePane.vala
src/Panes/FilesPane.vala
src/Panes/FontsPane.vala
src/Panes/MiscPane.vala
src/Panes/TerminalPane.vala
src/Widgets/Categories.vala

Use the virtual method for actual reset process

Categories: Refactor reset methods

---

src/Panes/AppearancePane.vala
src/Panes/FilesPane.vala
src/Panes/FontsPane.vala
src/Panes/TerminalPane.vala
src/Widgets/Categories.vala

- halign widgets against HeaderLabel
- Have 18px spacing for each setting and 24px for different sections

Redesign: Review spacing

---

src/Settings/ThemeSettings.vala
src/Widgets/Categories.vala

ThemeSettings: Fix incomplete list when failed to fetch themes

---

data/meson.build
data/pantheon-tweaks.metainfo.xml.in.in

This allows us preventing screenshot from being not up to date

metainfo: Set screenshot from project_version

---

src/Panes/AppearancePane.vala
src/Widgets/Categories.vala

- Generalization
- Rename DestinationButton to OpenButton
- Argument as a full path
- Show the given path in the translatable texts

Refactor OpenButton

---

src/Settings/XSettings.vala

- Make sure to update the value of `decoration_layout` at one time
- Prefer nested ifs than else if for better readability
- Leave example comments

refactor: XSettings: Make atomic and leave comments

---

io.github.pantheon_tweaks.pantheon-tweaks.yml

It's now in the baseapp finally!
flathub/io.elementary.BaseApp#30

chore: Flatpak: Remove granite

---

src/Model/StringIdObject.vala
src/Util/DropDownUtil.vala
src/Util/SchemaUtil.vala
src/Util/StringIdListUtil.vala
src/Util/StringListUtil.vala
src/Widgets/BasePane.vala
src/Widgets/Dialog.vala
src/Widgets/DropDownId.vala
src/Widgets/DropDownRow.vala
src/Widgets/OpenButton.vala

For consistency with existing sources.

style: Add PantheonTweaks namespace

---

src/Widgets/Categories.vala

- Set properties on initialization
- Distinct variable name
- Remove panes from stack when deconstruct

refactor: Refactor Categories

---

src/Panes/AppearancePane.vala
src/Panes/FilesPane.vala
src/Panes/FontsPane.vala
src/Panes/MiscPane.vala
src/Panes/TerminalPane.vala
src/Widgets/BasePane.vala

This allows us to explicit what each parameter is.

refactor: GObject-style construction

---

src/Panes/TerminalPane.vala

Originally from https://github.com/elementary-tweaks/elementary-tweaks/pull/144

feat: TerminalPane: Add cursor-shape preference
