pantheon-tweaks/pantheon-tweaks

src/Panes/AppearancePane.vala

elementary OS 6 will support an OS-wide dark preference, but this only works for apps that can detect this preference using `Granite.Settings.prefers_color_schema`; Third-party apps like Google Chrome, Slack, or Visual Studio Code are not switched to dark style according to this preference, and we still need to enable "Prefer dark variant" switch in elementary Tweaks to force these apps to use dark style.
However, I think the current label of this switch might be confusing, so I changed the label string.

AppearancePane: More descriptive label for dark style

---

src/Panes/FontsPane.vala
src/Widgets/Categories.vala

* Use `Gtk.FontButton.font` instead of `Gtk.FontButton.font_name` (deprecated since 3.22)
* Use `Gtk.FontButton.font` instead of `Gtk.FontButton.get_font_name` (deprecated since 3.22)

Fix deprecations

---

src/Widgets/Categories.vala

`Granite.HeaderLabel` is a start-aligned Gtk.Label with the Granite H4 style class, so we can use it instead of setting the same style by ourselves

Categories: Use Granite.HeaderLabel

---

src/Panes/AnimationsPane.vala

Removes the "enable animations" setting that is now available under the Accessibility pane. 
Fixes: https://github.com/elementary-tweaks/elementary-tweaks/issues/34

Remove animation setting

---

src/Panes/TerminalPane.vala
src/Settings/TerminalSettings.vala

Because it is already configurable in Terminal itself:

TerminalPane: Remove natural copy & paste setting

---

src/Panes/MiscPane.vala

- Put everything in `construct` to less scope of variables (this also allows us to use GLib.Settings.bind in a future PR)

MiscPane: Coding style

---

src/Settings/GtkSettings.vala
src/Util.vala

We see the following errors if we have never change the dark style settings:
```
** (io.elementary.switchboard:21479): WARNING **: 11:31:30.143: GtkSettings.vala:48: Error loading GTK+ Keyfile settings.ini: No such file or directory
** (io.elementary.switchboard:21479): WARNING **: 11:31:30.143: GtkSettings.vala:69: Error getting GTK+ int setting: Key file does not have group “Settings”
```
This PR fixes these warnings shown when target dirs/keyfiles doesn't exist.
Also, don't crush errors―I guess someone commented out this `warning (e.message);` because they knew this shows unwanted error messages about missing files. However, this prevent us from debugging errors if some errors occur in `enumerate_children` method.

Fix warnings when target dirs/keyfiles doesn't exist

---

src/Panes/AnimationsPane.vala
src/Settings/GalaSettings.vala

- Put everything in `construct` to less scope of variables
- Use GLib.Settings instead of deprecated Granite.Service.Settings

AnimationsPane: Clean code and use GLib.Settings

---

src/Panes/FontsPane.vala
src/Settings/GnomeSettings.vala

- Put everything in `construct` to less scope of variables
- Use GLib.Settings instead of deprecated Granite.Service.Settings

FontsPane: Clean code and use GLib.Settings

---

src/Panes/AppearancePane.vala
src/Settings/GtkSettings.vala

- Normal class initialization instead of singleton because the instance of GtkSettings is only used in AppearancePane
- Lint with vala-lint
Review in "Hide whitespace changes" mode.

GtkSettings: Clean code

---

meson.build
po/POTFILES
src/Panes/AnimationsPane.vala
src/Panes/AppearancePane.vala
src/Panes/AudiencePane.vala
src/Panes/FilesPane.vala
src/Panes/MiscPane.vala
src/Panes/TerminalPane.vala
src/Settings/ThemeSettings.vala
src/Widgets/Categories.vala

`Util.vala` contains three methods; two are used in AppearancePane to get system/icon/cursor themes and another is used in some Panes to check the existence of schemes used in them. It would be fine of these methods to be in Utils if they are used wildly in the project, but it's not, so it would be even more make sense to put them into more suitable files.

Move the methods in Utils to more suitable files

---

debian/copyright

Follows the copyright header in vala files.

deb-packaging: Fix copyright

---

src/Panes/AnimationsPane.vala
src/Panes/AudiencePane.vala
src/Panes/FilesPane.vala
src/Panes/MiscPane.vala
src/Panes/TerminalPane.vala
src/Widgets/Categories.vala

If the schema id is can't be found for some reason (e.g. when elementary changed schema id of some components in favor of RDNNed id on Juno), the content of the pane is not shown. However, there are no error/debug messages so users can't find why the content isn't shown.
If the plug can't detect schemas, not only hide the content but also hide the pane and listbox itself because this means it's not available on the system implicitly.
This design pattern is how elementary do in the Mouse & Touchpad Plug; it hides the touchegg pane & row if it's not installed on the system.

Hide PaneListItem if no schemas found

---

debian/control
meson.build

In order to prevent unintentional install to Hera like #68

Make sure to be available only on Odin or later

---

README.md

- Fix wrong code name (Juno is now called Hera)
- Add `-y` option to the apt commands
- Revert the installation way from PPA before 7ffec3285d112eb1405f595614e993bc6ce19f47. I confirmed now this way works on Odin Daily
- Omit `libswitchboard-2.0-dev` because it's included in `elementary-sdk` as a dependency

README: Update installation commands

---

src/Panes/AppearancePane.vala
src/Panes/TerminalPane.vala

Fix the following lint warnings:
```
src/Panes/AppearancePane.vala
84.120   warn    Line exceeds limit of 120 characters (currently 147 characters)   line-length
src/Panes/TerminalPane.vala
37.120   warn    Line exceeds limit of 120 characters (currently 121 characters)   line-length
47.120   warn    Line exceeds limit of 120 characters (currently 125 characters)   line-length
59.120   warn    Line exceeds limit of 120 characters (currently 173 characters)   line-length
```

Lint using vala-lint

---

data/pantheon-tweaks.appdata.xml.in
src/Settings/ThemeSettings.vala

These themes looks broken on Pantheon so don't show them in the theme chooser.

ThemeSettings: Ignore Adwaita/gnome/hicolor themes

---

meson.build
src/Config.vala.in
src/Tweaks.vala

Provides the directory where the locales are actually installed.
We are trying to package this on NixOS (as requested in https://github.com/NixOS/nixpkgs/issues/115222 and https://github.com/NixOS/nixpkgs/issues/135376), and due to NixOS 's special `localedir`, we cannot apply the translations without this patch. I think this should have no affect on elementary OS.
Similar PR: https://github.com/elementary/switchboard-plug-about/pull/229.
Thanks for reviewing this!

l10n: Correctly setup the locales

---

meson.build

We are trying to package this on NixOS (as requested in https://github.com/NixOS/nixpkgs/issues/115222 and https://github.com/NixOS/nixpkgs/issues/135376), on NixOS all packages are installed into their own immutable prefix. Because of this `switchboard_dep.get_pkgconfig_variable` will return a path from within switchboard's prefix and we cannot write to it. By using `define_variable` we can replace the `libdir` to be from the paths from meson. I think this should have no affect on elementary OS. 
Similar PR: https://github.com/elementary/switchboard-plug-about/pull/100.
Thanks for reviewing this!

build: fix install path for switchboard plug

---

src/Panes/AppearancePane.vala

Icons/cursors in `~/.local/share/icons` are not loaded on Odin as reported in #90. While I'm not sure this is due to Pantheon Tweaks or Pantheon itself, we should change these copies to the ones that works as expected for now

Correct cursor and icon theme dir copies

---

src/Panes/FontsPane.vala

The `applications-fonts` was renamed in https://github.com/elementary/icons/commit/946e0d82e004bd1548d837588ec540983d5a84f2

FontsPane: Fix icon missing with the latest icons update

---

src/Widgets/Categories.vala

The latest version of Gala introduces a feature that dim the parent window of dialogs but this only works when `transient_for` is set.

Set transient window for Reset dialog

---

data/meson.build
debian/control
meson.build

According to [the docs](https://mesonbuild.com/Reference-manual_functions.html#join_paths):
> *(since 0.49.0)* Using the `/` operator on strings is equivalent to calling [`join_paths()`](https://mesonbuild.com/Reference-manual_functions.html#join_paths).
This should be much simpler because it loses an extra set of parenthesis

meson: Replace join_paths with '/'

---

data/meson.build
debian/control
meson.build

I believed the latest version of valac on focal is 0.5x but it's not :sweat_smile:
```
ryonakano@ryonakano-pc:~/Projects/pantheon-tweaks$ LANG=C apt-cache policy valac
valac:
Installed: 0.48.20-0ubuntu1~20.04~valateam0
Candidate: 0.48.20-0ubuntu1~20.04~valateam0
Version table:
*** 0.48.20-0ubuntu1~20.04~valateam0 999
999 http://ppa.launchpad.net/elementary-os/os-patches/ubuntu focal/main amd64 Packages
100 /var/lib/dpkg/status
0.48.6-0ubuntu1 500
500 mirror://mirrors.ubuntu.com/mirrors.txt focal-updates/universe amd64 Packages
0.48.3-1 500
500 mirror://mirrors.ubuntu.com/mirrors.txt focal/universe amd64 Packages
```
We need to revert this for now until 0.49.0 or later get available on focal

Revert "meson: Replace join_paths with '/' (#137)"

---

src/Panes/TerminalPane.vala

Terminal now comes with color pallet feature starting from [6.1.0](https://github.com/elementary/terminal/releases/tag/6.1.0) (which is also available on current stable―Jólnir). And with that feature we can customize not only the background color but also font color, cursor color, and more.
Also, as far as I confirmed on elementary OS Early Access 7 this background preference no longer takes effect on Terminal.
These are the reasons why I decided to remove this preference from Pantheon Tweaks.

TerminalPane: Remove background color preference

---

data/meson.build
debian/control
meson.build
meson/post_install.py
po/meson.build

- Use `/` instead of `join_paths()` (added in [0.49.0](https://mesonbuild.com/Reference-manual_functions.html#join_paths))
- Use `get_variable()` instead of deprecated `get_pkgconfig_variable()` (added in [0.51.0](https://mesonbuild.com/Reference-manual_returned_dep.html#depget_variable))
- Remove unnecessary `--directory` argument from gettext
As a result we now require meson >= 0.51.0 with these changes.

meson: Use newer syntax

---

io.github.pantheon_tweaks.pantheon-tweaks.yml
start-pantheon-tweaks.sh

- Remove systemd config-opts and the unit file which is not used in Flatpak
- Do not separate modules for the wrapper script
- Add comment to the cleanup function in the wrapper script
See https://github.com/flathub/flathub/pull/5266 for suggested changes

Apply suggested changes from Flathub maintainers

---

src/Widgets/Categories.vala

This route failed to create directory, so don't try to open the directory that does not exist.

DestinationButton: Fix double error dialog when directory creation failed

---

io.github.pantheon_tweaks.pantheon-tweaks.yml

- Cleanup `/app/bin/dconf` because we use dconf as a dependency and the binary is not necessary
- Cleanup AppStream metainfo of stylesheet and granite
- Cleanup granite icon

Flatpak: Lessen package size

---

0001-lib-Include-stylesheet-in-the-library.patch
io.github.pantheon_tweaks.pantheon-tweaks.yml
meson.build
src/Tweaks.vala
src/Widgets/Categories.vala

Granite.SimpleSettingsPage has been deprecated since Granite 7.5.0.

Replace Granite.SimpleSettingsPage with Switchboard.SettingsPage

---

meson.build
src/Panes/TerminalPane.vala

- Use `Granite.HeaderLabel.secondary_text` for the description text instead of the custom dim label
- Remove trailing period from the description text
- Leave block comment for legiblity

TerminalPane: Redesign

---

src/Panes/FontsPane.vala

- Leave block comment for legiblity
- Avoid using useless `font_button_new` method

FontsPane: Redesign

---

src/Panes/FilesPane.vala

- Add the description text using `Granite.HeaderLabel.secondary_text`
- Leave block comment for legiblity

FilesPane: Redesign

---

src/Panes/AppearancePane.vala

- Add the description text using `Granite.HeaderLabel.secondary_text`
- Leave block comment for legiblity
- Explicit switch in the variable name

AppearancePane: Redesign

---

src/Panes/TerminalPane.vala

Fixes the issue that resetting TerminalPane settings also resets natural-copy-paste settings that we no longer provide a widget to set in Tweaks.

TerminalPane: Do not reset natural-copy-paste setting

---

src/Widgets/Categories.vala

Prevent the window width from being smaller than the view:

Categories: Fix window width can be smaller than view

---

src/Panes/AppearancePane.vala

Fixes #229
This schema is removed as unused in the following commit:
https://github.com/elementary/gala/commit/66679ca79662cff3eca5b4d850aeec4bad23bbd4

AppearancePane: Remove access to Gala's appearance schema

---

src/Panes/AppearancePane.vala
src/Settings/ThemeSettings.vala

Wrap methods that have magic parameters. Also rename get_themes to fetch_themes because this is not a getter method.

ThemeSettings: Split theme methods

---

data/styles/SettingsPage.scss
data/styles/SettingsSidebar.scss

Do not use a number for font-weight, otherwise serif font is used for these labels where sans-serif is expected.
Same fix with https://github.com/elementary/stylesheet/commit/a0af9bde6bba63b4b8850b042bbd8ee4a48f57ab and https://github.com/elementary/stylesheet/commit/df37637701b784a197dec6f5901f2e69fe45ed49

Set font-weight as bold

---

src/Config.vala.in
src/Tweaks.vala

So that we can distinguish these are not normal constants but build configurations.

Config: Add namespace

---

io.github.pantheon_tweaks.pantheon-tweaks.yml
meson.build
meson_options.txt
src/Config.vala.in
src/Settings/ThemeSettings.vala

Reasons:
- It wouldn't happen that the root directory of system themes changes every time when the app launches, so it should be fine that being a build option instead of a runtime environment variable.
- This directory is completely different, which means it won't work just adding a prefix to `/usr/share/`, on some environments like NixOS. NixOS seems to [patch the source](https://github.com/NixOS/nixpkgs/blob/465eab85d222e5d52d46987edfb6f84b7c7723ed/pkgs/by-name/pa/pantheon-tweaks/package.nix#L48-L51) to refer correct directory. So allow packagers to set an arbitrary path instead of `/usr/share/`.

Provide system theme rootdir as a build option

---

io.github.pantheon_tweaks.pantheon-tweaks.yml

From https://docs.flatpak.org/en/latest/flatpak-builder-command-reference.html:
> Note, "app-id" is deprecated and preserved only for backwards compatibility.

Flatpak: Use id instead of deprecated app-id

---

io.github.pantheon_tweaks.pantheon-tweaks.yml

It looks like granite-7 is installed into /app/lib64 where pkg-config doesn't search for

Fix build failing when building switchboard

---

data/icons/pantheon-tweaks.svg

Official apps on Pantheon commonly uses icons in a square shape, so make sure that our icons looks good alongside them.

Redesign to square icon

---

.github/workflows/main.yml

This fixes the CI failing with `Error: Create Artifact Container failed: The artifact name is not valid` error.

Actions: Update flatpak-builder from v6 to v6.4

---

io.github.pantheon_tweaks.pantheon-tweaks.yml

So that we can use the simple git pattern for Flatpak External Data Checker

chore: Use git for elementary modules

---

data/pantheon-tweaks.metainfo.xml.in.in

Support for `pantheon:dark` is added in AppStream 1.0.4:
https://github.com/ximion/appstream/commit/42a5e66dced26ce0871210acb4d75e4a14785f3a
And flatpak-builder comes with AppStream 1.0.4:
```
user@elementary-8-daily:~/work/pantheon-tweaks$ flatpak run --command=sh org.flatpak.Builder
sh: __bp_precmd_invoke_cmd: command not found
sh: __bp_interactive_mode: command not found
[📦 org.flatpak.Builder pantheon-tweaks]$ appstreamcli --version
AppStream version: 1.0.4
sh: __bp_precmd_invoke_cmd: command not found
sh: __bp_interactive_mode: command not found
[📦 org.flatpak.Builder pantheon-tweaks]$
```
So, using this environment style should no longer cause screenshot-invalid-env-style warning and linter error.

chore: metainfo: Enable dark screenshot

---

io.github.pantheon_tweaks.pantheon-tweaks.yml

We've been using the GNOME runtime and bundle everything we need for Pantheon since we published Panthen Tweaks on Flathub because the baseapp is not well maintained and obsolete at that time: https://github.com/flathub/flathub/pull/5266#discussion_r1606020520
Now, we have latest and maintained branch of the baseapp, so let's base on it to avoid duplicated work here.

feat: Flatpak: Use io.elementary.BaseApp//circe-24.08

---

io.github.pantheon_tweaks.pantheon-tweaks.yml

It's now included in latest version of the baseapp:
https://github.com/flathub/io.elementary.BaseApp/commit/efbeaf3fcbd8ebc6010bedd0c702f0e663b0b049

chore: Flatpak: Remove sassc

---

src/Settings/XSettings.vala

This fixes the issue that choosing another window control layout then backing to elementary results different window layout; `close:maximize,menu`, not the default `close:menu,maximize`.

bugfix: ThemeSettings: Correct position to insert menu

---

src/Panes/FontsPane.vala
src/Panes/TerminalPane.vala
src/Widgets/BasePane.vala
src/Widgets/OpenButton.vala

- Use `Gtk.Widget.present ()` instead of [deprecated `Gtk.Widget.show ()`](https://docs.gtk.org/gtk4/method.Widget.show.html)
- Fix `-Wincompatible-pointer-types` warnings of `GLib.Settings.bind_with_mapping ()`

chore: Fix some build warnings

---

meson.build
src/Tweaks.vala

[`GLib.ApplicationFlags.FLAGS_NONE`](https://valadoc.org/gio-2.0/GLib.ApplicationFlags.FLAGS_NONE.html) has been deprecated since 2.74.

chore: Use GLib.ApplicationFlags.DEFAULT_FLAGS

---

src/MainWindow.vala
src/Tweaks.vala

The previous code only applies color scheme preference to the main window and its followings. This change is meaningless in our code because we have no other windows but this makes more sense.

fix: Apply color scheme preference to app-wide

---

meson.build
src/Widgets/Categories.vala
src/Widgets/Dialog.vala
src/Widgets/OpenButton.vala

Unify code between 2 error dialogs:

chore: Generalize error dialogs

---

src/Panes/AppearancePane.vala
src/Panes/FilesPane.vala
src/Panes/FontsPane.vala
src/Panes/MiscPane.vala
src/Panes/TerminalPane.vala
src/Widgets/BasePane.vala

We attach each box into the content area, so it's meaningless that the content area is an Gtk.Grid.

refactor: Replace Gtk.Grid with Gtk.Box
